var quality = {
    '0': { // 0 -21
        itag: 5,
        container: 'flv',
        resolution: '240p',
        encoding: 'Sorenson H.283',
        profile: null,
        bitrate: '0.25',
        audioEncoding: 'mp3',
        audioBitrate: 64,
    },

    '1': {
        itag: 6,
        container: 'flv',
        resolution: '270p',
        encoding: 'Sorenson H.263',
        profile: null,
        bitrate: '0.8',
        audioEncoding: 'mp3',
        audioBitrate: 64,
    },

    '2': {
        itag: 13,
        container: '3gp',
        resolution: null,
        encoding: 'MPEG-4 Visual',
        profile: null,
        bitrate: '0.5',
        audioEncoding: 'aac',
        audioBitrate: null,
    },

    '3': {
        itag: 17,
        container: '3gp',
        resolution: '144p',
        encoding: 'MPEG-4 Visual',
        profile: 'simple',
        bitrate: '0.05',
        audioEncoding: 'aac',
        audioBitrate: 24,
    },

    '4': {
        itag: 18,
        container: 'mp4',
        resolution: '360p',
        encoding: 'H.264',
        profile: 'baseline',
        bitrate: '0.5',
        audioEncoding: 'aac',
        audioBitrate: 96,
    },

    '5': {
        itag: 22,
        container: 'mp4',
        resolution: '720p',
        encoding: 'H.264',
        profile: 'high',
        bitrate: '2-3',
        audioEncoding: 'aac',
        audioBitrate: 192,
    },

    '6': {
        itag: 34,
        container: 'flv',
        resolution: '360p',
        encoding: 'H.264',
        profile: 'main',
        bitrate: '0.5',
        audioEncoding: 'aac',
        audioBitrate: 128,
    },

    '7': {
        itag: 35,
        container: 'flv',
        resolution: '480p',
        encoding: 'H.264',
        profile: 'main',
        bitrate: '0.8-1',
        audioEncoding: 'aac',
        audioBitrate: 128,
    },

    '8': {
        itag: 36,
        container: '3gp',
        resolution: '240p',
        encoding: 'MPEG-4 Visual',
        profile: 'simple',
        bitrate: '0.175',
        audioEncoding: 'aac',
        audioBitrate: 32,
    },

    '9': {
        itag: 37,
        container: 'mp4',
        resolution: '1080p',
        encoding: 'H.264',
        profile: 'high',
        bitrate: '3-5.9',
        audioEncoding: 'aac',
        audioBitrate: 192,
    },

    '10': {
        itag: 38,
        container: 'mp4',
        resolution: '3072p',
        encoding: 'H.264',
        profile: 'high',
        bitrate: '3.5-5',
        audioEncoding: 'aac',
        audioBitrate: 192,
    },

    '11': {
        itag: 43,
        container: 'webm',
        resolution: '360p',
        encoding: 'VP8',
        profile: null,
        bitrate: '0.5-0.75',
        audioEncoding: 'vorbis',
        audioBitrate: 128,
    },

    '12': {
        itag: 44,
        container: 'webm',
        resolution: '480p',
        encoding: 'VP8',
        profile: null,
        bitrate: '1',
        audioEncoding: 'vorbis',
        audioBitrate: 128,
    },

    '13': {
        itag: 45,
        container: 'webm',
        resolution: '720p',
        encoding: 'VP8',
        profile: null,
        bitrate: '2',
        audioEncoding: 'vorbis',
        audioBitrate: 192,
    },

    '14': {
        itag: 46,
        container: 'webm',
        resolution: '1080p',
        encoding: 'vp8',
        profile: null,
        bitrate: null,
        audioEncoding: 'vorbis',
        audioBitrate: 192,
    },

    '15': {
        itag: 82,
        container: 'mp4',
        resolution: '360p',
        encoding: 'H.264',
        profile: '3d',
        bitrate: '0.5',
        audioEncoding: 'aac',
        audioBitrate: 96,
    },

    '16': {
        itag: 83,
        container: 'mp4',
        resolution: '240p',
        encoding: 'H.264',
        profile: '3d',
        bitrate: '0.5',
        audioEncoding: 'aac',
        audioBitrate: 96,
    },

    '17': {
        itag: 84,
        container: 'mp4',
        resolution: '720p',
        encoding: 'H.264',
        profile: '3d',
        bitrate: '2-3',
        audioEncoding: 'aac',
        audioBitrate: 192,
    },

    '18': {
        itag: 85,
        container: 'mp4',
        resolution: '1080p',
        encoding: 'H.264',
        profile: '3d',
        bitrate: '3-4',
        audioEncoding: 'aac',
        audioBitrate: 192,
    },

    '19': {
        itag: 100,
        container: 'webm',
        resolution: '360p',
        encoding: 'VP8',
        profile: '3d',
        bitrate: null,
        audioEncoding: 'vorbis',
        audioBitrate: 128,
    },

    '20': {
        itag: 101,
        container: 'webm',
        resolution: '360p',
        encoding: 'VP8',
        profile: '3d',
        bitrate: null,
        audioEncoding: 'vorbis',
        audioBitrate: 192,
    },

    '21': {
        itag: 102,
        container: 'webm',
        resolution: '720p',
        encoding: 'VP8',
        profile: '3d',
        bitrate: null,
        audioEncoding: 'vorbis',
        audioBitrate: 192,
    },

    // DASH (video only) 21- 54
    '22': {
        itag: 133,
        container: 'mp4',
        resolution: '240p',
        encoding: 'H.264',
        profile: 'main',
        bitrate: '0.2-0.3',
        audioEncoding: null,
        audioBitrate: null,
    },

    '23': {
        itag: 134,
        container: 'mp4',
        resolution: '360p',
        encoding: 'H.264',
        profile: 'main',
        bitrate: '0.3-0.4',
        audioEncoding: null,
        audioBitrate: null,
    },

    '24': {
        itag: 135,
        container: 'mp4',
        resolution: '480p',
        encoding: 'H.264',
        profile: 'main',
        bitrate: '0.5-1',
        audioEncoding: null,
        audioBitrate: null,
    },

    '25': {
        itag: 136,
        container: 'mp4',
        resolution: '720p',
        encoding: 'H.264',
        profile: 'main',
        bitrate: '1-1.5',
        audioEncoding: null,
        audioBitrate: null,
    },

    '26': {
        itag: 137,
        container: 'mp4',
        resolution: '1080p',
        encoding: 'H.264',
        profile: 'high',
        bitrate: '2.5-3',
        audioEncoding: null,
        audioBitrate: null,
    },

    '27': {
        itag: 138,
        container: 'mp4',
        resolution: '4320p',
        encoding: 'H.264',
        profile: 'high',
        bitrate: '13.5-25',
        audioEncoding: null,
        audioBitrate: null,
    },

    '28': {
        itag: 160,
        container: 'mp4',
        resolution: '144p',
        encoding: 'H.264',
        profile: 'main',
        bitrate: '0.1',
        audioEncoding: null,
        audioBitrate: null,
    },

    '29': {
        itag: 242,
        container: 'webm',
        resolution: '240p',
        encoding: 'VP9',
        profile: 'profile 0',
        bitrate: '0.1-0.2',
        audioEncoding: null,
        audioBitrate: null,
    },

    '30': {
        itag: 243,
        container: 'webm',
        resolution: '360p',
        encoding: 'VP9',
        profile: 'profile 0',
        bitrate: '0.25',
        audioEncoding: null,
        audioBitrate: null,
    },

    '31': {
        itag: 244,
        container: 'webm',
        resolution: '480p',
        encoding: 'VP9',
        profile: 'profile 0',
        bitrate: '0.5',
        audioEncoding: null,
        audioBitrate: null,
    },

    '32': {
        itag: 247,
        container: 'webm',
        resolution: '720p',
        encoding: 'VP9',
        profile: 'profile 0',
        bitrate: '0.7-0.8',
        audioEncoding: null,
        audioBitrate: null,
    },

    '33': {
        itag: 248,
        container: 'webm',
        resolution: '1080p',
        encoding: 'VP9',
        profile: 'profile 0',
        bitrate: '1.5',
        audioEncoding: null,
        audioBitrate: null,
    },

    '34': {
        itag: 264,
        container: 'mp4',
        resolution: '1440p',
        encoding: 'H.264',
        profile: 'high',
        bitrate: '4-4.5',
        audioEncoding: null,
        audioBitrate: null,
    },

    '35': {
        itag: 266,
        container: 'mp4',
        resolution: '2160p',
        encoding: 'H.264',
        profile: 'high',
        bitrate: '12.5-16',
        audioEncoding: null,
        audioBitrate: null,
    },

    '36': {
        itag: 271,
        container: 'webm',
        resolution: '1440p',
        encoding: 'VP9',
        profile: 'profile 0',
        bitrate: '9',
        audioEncoding: null,
        audioBitrate: null,
    },

    '37': {
        itag: 272,
        container: 'webm',
        resolution: '4320p',
        encoding: 'VP9',
        profile: 'profile 0',
        bitrate: '20-25',
        audioEncoding: null,
        audioBitrate: null,
    },

    '38': {
        itag: 278,
        container: 'webm',
        resolution: '144p 15fps',
        encoding: 'VP9',
        profile: 'profile 0',
        bitrate: '0.08',
        audioEncoding: null,
        audioBitrate: null,
    },

    '39': {
        itag: 298,
        container: 'mp4',
        resolution: '720p',
        encoding: 'H.264',
        profile: 'main',
        bitrate: '3-3.5',
        audioEncoding: null,
        audioBitrate: null,
    },

    '40': {
        itag: 299,
        container: 'mp4',
        resolution: '1080p',
        encoding: 'H.264',
        profile: 'high',
        bitrate: '5.5',
        audioEncoding: null,
        audioBitrate: null,
    },

    '41': {
        itag: 302,
        container: 'webm',
        resolution: '720p HFR',
        encoding: 'VP9',
        profile: 'profile 0',
        bitrate: '2.5',
        audioEncoding: null,
        audioBitrate: null,
    },

    '42': {
        itag: 303,
        container: 'webm',
        resolution: '1080p HFR',
        encoding: 'VP9',
        profile: 'profile 0',
        bitrate: '5',
        audioEncoding: null,
        audioBitrate: null,
    },

    '43': {
        itag: 308,
        container: 'webm',
        resolution: '1440p HFR',
        encoding: 'VP9',
        profile: 'profile 0',
        bitrate: '10',
        audioEncoding: null,
        audioBitrate: null,
    },

    '44': {
        itag: 313,
        container: 'webm',
        resolution: '2160p',
        encoding: 'VP9',
        profile: 'profile 0',
        bitrate: '13-15',
        audioEncoding: null,
        audioBitrate: null,
    },

    '45': {
        itag: 315,
        container: 'webm',
        resolution: '2160p HFR',
        encoding: 'VP9',
        profile: 'profile 0',
        bitrate: '20-25',
        audioEncoding: null,
        audioBitrate: null,
    },

    '46': {
        itag: 330,
        container: 'webm',
        resolution: '144p HDR, HFR',
        encoding: 'VP9',
        profile: 'profile 2',
        bitrate: '0.08',
        audioEncoding: null,
        audioBitrate: null,
    },

    '47': {
        itag: 331,
        container: 'webm',
        resolution: '240p HDR, HFR',
        encoding: 'VP9',
        profile: 'profile 2',
        bitrate: '0.1-0.15',
        audioEncoding: null,
        audioBitrate: null,
    },

    '48': {
        itag: 332,
        container: 'webm',
        resolution: '360p HDR, HFR',
        encoding: 'VP9',
        profile: 'profile 2',
        bitrate: '0.25',
        audioEncoding: null,
        audioBitrate: null,
    },

    '49': {
        itag: 333,
        container: 'webm',
        resolution: '240p HDR, HFR',
        encoding: 'VP9',
        profile: 'profile 2',
        bitrate: '0.5',
        audioEncoding: null,
        audioBitrate: null,
    },

    '50': {
        itag: 334,
        container: 'webm',
        resolution: '720p HDR, HFR',
        encoding: 'VP9',
        profile: 'profile 2',
        bitrate: '1',
        audioEncoding: null,
        audioBitrate: null,
    },

    '51': {
        itag: 335,
        container: 'webm',
        resolution: '1080p HDR, HFR',
        encoding: 'VP9',
        profile: 'profile 2',
        bitrate: '1.5-2',
        audioEncoding: null,
        audioBitrate: null,
    },

    '52': {
        itag: 336,
        container: 'webm',
        resolution: '1440p HDR, HFR',
        encoding: 'VP9',
        profile: 'profile 2',
        bitrate: '5-7',
        audioEncoding: null,
        audioBitrate: null,
    },

    '53': {
        itag: 337,
        container: 'webm',
        resolution: '2160p HDR, HFR',
        encoding: 'VP9',
        profile: 'profile 2',
        bitrate: '12-14',
        audioEncoding: null,
        audioBitrate: null,
    },

    // DASH (audio only) 54 - 63
    '55': {
        itag: 139,
        container: 'mp4',
        resolution: null,
        encoding: null,
        profile: null,
        bitrate: null,
        audioEncoding: 'aac',
        audioBitrate: 48,
    },

    '56': {
        itag: 140,
        container: 'm4a',
        resolution: null,
        encoding: null,
        profile: null,
        bitrate: null,
        audioEncoding: 'aac',
        audioBitrate: 128,
    },

    '57': {
        itag: 141,
        container: 'mp4',
        resolution: null,
        encoding: null,
        profile: null,
        bitrate: null,
        audioEncoding: 'aac',
        audioBitrate: 256,
    },

    '58': {
        itag: 171,
        container: 'webm',
        resolution: null,
        encoding: null,
        profile: null,
        bitrate: null,
        audioEncoding: 'vorbis',
        audioBitrate: 128,
    },

    '59': {
        itag: 172,
        container: 'webm',
        resolution: null,
        encoding: null,
        profile: null,
        bitrate: null,
        audioEncoding: 'vorbis',
        audioBitrate: 192,
    },

    '60': {
        itag: 249,
        container: 'webm',
        resolution: null,
        encoding: null,
        profile: null,
        bitrate: null,
        audioEncoding: 'opus',
        audioBitrate: 48,
    },
    '61': {
        itag: 250,
        container: 'webm',
        resolution: null,
        encoding: null,
        profile: null,
        bitrate: null,
        audioEncoding: 'opus',
        audioBitrate: 64,
    },
    '62': {
        itag: 251,
        container: 'webm',
        resolution: null,
        encoding: null,
        profile: null,
        bitrate: null,
        audioEncoding: 'opus',
        audioBitrate: 160,
    },

    // Live streaming 63 - 73
    '63': {
        itag: 91,
        container: 'ts',
        resolution: '144p',
        encoding: 'H.264',
        profile: 'main',
        bitrate: '0.1',
        audioEncoding: 'aac',
        audioBitrate: 48,
    },

    '64': {
        itag: 92,
        container: 'ts',
        resolution: '240p',
        encoding: 'H.264',
        profile: 'main',
        bitrate: '0.15-0.3',
        audioEncoding: 'aac',
        audioBitrate: 48,
    },

    '65': {
        itag: 93,
        container: 'ts',
        resolution: '360p',
        encoding: 'H.264',
        profile: 'main',
        bitrate: '0.5-1',
        audioEncoding: 'aac',
        audioBitrate: 128,
    },

    '66': {
        itag: 94,
        container: 'ts',
        resolution: '480p',
        encoding: 'H.264',
        profile: 'main',
        bitrate: '0.8-1.25',
        audioEncoding: 'aac',
        audioBitrate: 128,
    },

    '67': {
        itag: 95,
        container: 'ts',
        resolution: '720p',
        encoding: 'H.264',
        profile: 'main',
        bitrate: '1.5-3',
        audioEncoding: 'aac',
        audioBitrate: 256,
    },

    '68': {
        itag: 96,
        container: 'ts',
        resolution: '1080p',
        encoding: 'H.264',
        profile: 'high',
        bitrate: '2.5-6',
        audioEncoding: 'aac',
        audioBitrate: 256,
    },

    '69': {
        itag: 120,
        container: 'flv',
        resolution: '720p',
        encoding: 'H.264',
        profile: 'Main@L3.1',
        bitrate: '2',
        audioEncoding: 'aac',
        audioBitrate: 128,
    },

    '70': {
        itag: 127,
        container: 'ts',
        resolution: null,
        encoding: null,
        profile: null,
        bitrate: null,
        audioEncoding: 'aac',
        audioBitrate: 96,
    },

    '71': {
        itag: 128,
        container: 'ts',
        resolution: null,
        encoding: null,
        profile: null,
        bitrate: null,
        audioEncoding: 'aac',
        audioBitrate: 96,
    },

    '72': {
        itag: 132,
        container: 'ts',
        resolution: '240p',
        encoding: 'H.264',
        profile: 'baseline',
        bitrate: '0.15-0.2',
        audioEncoding: 'aac',
        audioBitrate: 48,
    },

    '73': {
        itag: 151,
        container: 'ts',
        resolution: '720p',
        encoding: 'H.264',
        profile: 'baseline',
        bitrate: '0.05',
        audioEncoding: 'aac',
        audioBitrate: 24,
    },
}

module.exports = {
    quality
}